# Generated by Django 5.0 on 2023-12-15 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='cart_user',
            new_name='order_user',
        ),
    ]
