# Generated by Django 5.0 on 2023-12-18 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_book_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='slug',
        ),
    ]
