# Generated by Django 5.0 on 2023-12-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_orderitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='bstore/static/book_covers/'),
        ),
    ]
